---
- name: restart containerd
  command: /bin/true
  notify:
    - Containerd | reload containerd
    - Containerd | pause while containerd restarts
    - Containerd | wait for containerd

- name: Containerd | reload containerd
  service:
    name: containerd
    state: restarted

- name: Containerd | pause while containerd restarts
  pause:
    seconds: 5
    prompt: "Waiting for containerd restart"

- name: Containerd | wait for containerd
  command: "{{ containerd_bin_dir }}/ctr images ls -q"
  register: containerd_ready
  retries: 10
  delay: 5
  until: containerd_ready.rc == 0
